services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: demo_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
      LANG: ja_JP.UTF-8
      LANGUAGE: ja_JP:ja
      LC_ALL: ja_JP.UTF-8
    ports:
      - "3307:3306"
    volumes:
      - ./scripts/insert.sql:/docker-entrypoint-initdb.d/insert.sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
